name: Checking pull request

on: pull_request

jobs:
  checkin:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: NPM Clean Install
      run: npm ci
    - name: ESLint
      run: npm run lint:fix
    - name: TypeScript
      run: npm run typecheck
    
